#!/bin/bash

scriptpath="$(readlink -f "${BASH_SOURCE[0]}")"
scriptdir=$(dirname "${scriptpath}")

echo "start-script PID = $$."

# These fail ('daemon' is exited when 'gnome-terminal' exits):
# nohup sudo ... & disown
# sudo ... & disown
# sudo ... &
sudo -b -u kjstrand nohup "${scriptdir}/daemon_proc" >> /tmp/daemon_instance_$$

